<Project>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <AvaloniaVersion>12.1.3</AvaloniaVersion>
    <Version>0.1.0</Version>
    <Authors>drasticactions</Authors>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/drasticactions/avawpf</PackageProjectUrl>
    <RepositoryUrl>https://github.com/drasticactions/avawpf</RepositoryUrl>
    <PackageTags>avalonia;theme;avaloniaui;wpf;aero;luna;classic;fluent</PackageTags>
    <RepositoryType>git</RepositoryType>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <AvaWpfRepoRoot>$(MSBuildThisFileDirectory)</AvaWpfRepoRoot>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>$(AvaWpfRepoRoot)Key.snk</AssemblyOriginatorKeyFile>
    <PublicKey>00240000048000009400000006020000002400005253413100040000010001005311bd88d09f39da8d0a7814421594e8769c2c6af9b162a58a5c531868178ee6f8c3a108ffef4035eebe195bc06615043564b1c319b5b83be9ee8fae7f99a5b0b52cab19f8aabb66acbe9384dfda7a5d359e6b34ac3f7907db45f2c0c33c2bb4290ca55adc414a1823888a92d9b9f61c32f48d391be17000f3032e0b5146b48b</PublicKey>
  </PropertyGroup>

  <PropertyGroup Condition="'$(AvaWpfIsLibrary)' != 'false'">
    <IsTrimmable>true</IsTrimmable>
    <IsAotCompatible>true</IsAotCompatible>
    <EnableTrimAnalyzer>true</EnableTrimAnalyzer>
    <SuppressTrimAnalysisWarnings>false</SuppressTrimAnalysisWarnings>
    <TrimmerSingleWarn>false</TrimmerSingleWarn>
    <ILLinkTreatWarningsAsErrors>true</ILLinkTreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup Condition="'$(AvaWpfIsLibrary)' != 'false'">
    <None Include="$(AvaWpfRepoRoot)README.md" Pack="true" PackagePath="\" Visible="false" />
    <None Include="$(AvaWpfRepoRoot)NOTICE.md" Pack="true" PackagePath="\" Visible="false" />
    <None Include="$(AvaWpfRepoRoot)LICENSE.md" Pack="true" PackagePath="\" Visible="false" />
  </ItemGroup>

</Project>
