using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using Xunit;

namespace AvaWpf.Theme.Tests;

/// <summary>
/// Every storyboard of the WPF sources (MotionInventory.g.cs, generated by tools/wpf-tokens) has an AvaWpf
/// implementation. The ledger below names the AvaWpf ControlTheme files that implement each fragment's
/// motion; a storyboard with a duration must be animated there (Transitions, Style.Animations or an Animation), a
/// zero-length one (an instant VSM state) needs only the state style.
/// </summary>
public class MotionInventoryTests
{
    /// <summary>WPF fragment → the AvaWpf control files that carry its motion ("DataGrid:" files live in AvaWpf.DataGrid).</summary>
    private static readonly Dictionary<string, string[]> s_ledger = new(StringComparer.Ordinal)
    {
        ["Calendar"] = ["Calendar", "CalendarItem", "CalendarButton", "CalendarDayButton"],
        ["DatePicker"] = ["CalendarDatePicker", "DatePicker", "_CalendarDatePickerParts", "_DatePickerParts"],
        ["ProgressBar"] = ["ProgressBar"],
        ["ComboBox"] = ["ComboBox", "_ComboBoxToggleButton"],
        ["ContextMenu"] = ["ContextMenu"],
        ["Expander"] = ["Expander", "_ExpanderToggleButton"],
        ["MenuItem"] = ["MenuItem"],
        ["RadioButton"] = ["RadioButton"],
        ["ScrollBar"] = ["ScrollBar", "_ScrollBar"],
        ["Slider"] = ["Slider"],
        // WPF Fluent's TabControl.xaml holds the TabItem style whose disabled state fades.
        ["TabControl"] = ["TabControl", "TabItem"],
        // WPF Fluent's ToolBar.xaml ToolBarButtonBaseStyle is the Button.toolbar look.
        ["ToolBar"] = ["Button", "ToggleButton"],
        ["TreeViewItem"] = ["TreeViewItem"],
        ["DataGrid"] = ["DataGrid:DataGridCell", "DataGrid:DataGridRowHeader", "DataGrid:DataGridColumnHeader", "DataGrid:DataGrid"],
    };

    private static readonly Regex s_animation = new(@"<Transitions>|<Animation\b|Style\.Animations|Transition\s+Property=", RegexOptions.Compiled);

    public static TheoryData<string, string, string, string, double> Entries()
    {
        var data = new TheoryData<string, string, string, string, double>();
        foreach (var m in MotionInventory.All)
        {
            data.Add(m.Family, m.Fragment, m.Owner, m.Trigger, m.DurationMs);
        }

        return data;
    }

    [Theory]
    [MemberData(nameof(Entries))]
    public void Every_Storyboard_Has_An_Implementation(string family, string fragment, string owner, string trigger, double durationMs)
    {
        Assert.True(s_ledger.TryGetValue(fragment, out var names), $"{family} {fragment}: no ledger entry for {owner} {trigger}");
        var texts = Files(Enum.Parse<ThemeFamily>(family), names).ToList();
        Assert.True(texts.Count > 0, $"{family} {fragment}: none of {string.Join(", ", names)} exists");
        if (durationMs > 0)
        {
            Assert.True(texts.Any(t => s_animation.IsMatch(t)), $"{family} {fragment} {owner} {trigger} ({durationMs} ms) is not animated in {string.Join(", ", names)}");
        }
    }

    private static IEnumerable<string> Files(ThemeFamily family, string[] names)
    {
        var theme = ThemeXaml.ControlFiles(family).ToDictionary(f => f.Name, f => f.Text);
        foreach (var name in names)
        {
            if (name.StartsWith("DataGrid:", StringComparison.Ordinal))
            {
                foreach (var t in AddOnFiles("AvaWpf.DataGrid", family, name["DataGrid:".Length..]))
                {
                    yield return t;
                }
            }
            else if (theme.TryGetValue(name + ".axaml", out var text))
            {
                yield return text;
            }
        }
    }

    private static IEnumerable<string> AddOnFiles(string project, ThemeFamily family, string name)
    {
        var root = RepoRoot();
        if (root is null)
        {
            yield break;
        }

        var themes = Path.Combine(root, "src", project, "Themes");
        var own = Path.Combine(themes, family.ToString(), "Controls", name + ".axaml");
        if (File.Exists(own))
        {
            yield return File.ReadAllText(own);
            yield break;
        }

        foreach (var dir in Directory.GetDirectories(Path.Combine(themes, "Shared")))
        {
            var group = Path.GetFileName(dir);
            var members = group switch
            {
                "All" => Enum.GetNames<ThemeFamily>(),
                "AllClassic" => Enum.GetNames<ThemeFamily>().Where(n => n != "Fluent").ToArray(),
                _ => group.Split('+'),
            };
            var file = Path.Combine(dir, name + ".axaml");
            if (members.Contains(family.ToString()) && File.Exists(file))
            {
                yield return File.ReadAllText(file);
            }
        }
    }

    private static string? RepoRoot()
    {
        for (var dir = new DirectoryInfo(AppContext.BaseDirectory); dir is not null; dir = dir.Parent)
        {
            if (File.Exists(Path.Combine(dir.FullName, "AvaWpf.slnx")))
            {
                return dir.FullName;
            }
        }

        return null;
    }
}
