// <auto-generated>
// Generated by tools/wpf-tokens/wpf-tokens.cs. Do not edit.
// </auto-generated>
using Avalonia.Controls;
using Avalonia.Markup.Xaml;

namespace AvaWpf.Themes.Fluent;

/// <summary>The Fluent HighContrast tokens.</summary>
internal partial class TokensHighContrast : ResourceDictionary
{
    public TokensHighContrast()
    {
        AvaloniaXamlLoader.Load(this);
    }
}
