// <auto-generated>
// Generated by tools/wpf-tokens/wpf-tokens.cs. Do not edit.
// </auto-generated>
using Avalonia.Controls;
using Avalonia.Markup.Xaml;

namespace AvaWpf.Themes.Fluent;

/// <summary>The Fluent Dark tokens.</summary>
internal partial class TokensDark : ResourceDictionary
{
    public TokensDark()
    {
        AvaloniaXamlLoader.Load(this);
    }
}
