<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>AvaWpf.Explorer</RootNamespace>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\AvaWpf.Theme\AvaWpf.Theme.csproj" />
    <ProjectReference Include="..\..\..\src\AvaWpf.Controls\AvaWpf.Controls.csproj" />
    <ProjectReference Include="..\..\..\src\AvaWpf.Fonts\AvaWpf.Fonts.csproj" />
    <ProjectReference Include="..\..\AvaWpf.Samples.Common\AvaWpf.Samples.Common.csproj" />
  </ItemGroup>

</Project>
