// <auto-generated>
// Generated by tools/wpf-tokens/wpf-tokens.cs. Do not edit.
// </auto-generated>
using Avalonia.Controls;
using Avalonia.Markup.Xaml;

namespace AvaWpf.Themes.Luna;

/// <summary>The Luna Metallic, Light tokens.</summary>
internal partial class TokensMetallicLight : ResourceDictionary
{
    public TokensMetallicLight()
    {
        AvaloniaXamlLoader.Load(this);
    }
}
