// <auto-generated>
// Generated by tools/wpf-tokens/wpf-tokens.cs. Do not edit.
// </auto-generated>
using Avalonia.Controls;
using Avalonia.Markup.Xaml;

namespace AvaWpf.Themes.Luna;

/// <summary>The Luna Homestead, Dark (derived; see tools/wpf-tokens/dark/luna.toml) tokens.</summary>
internal partial class TokensHomesteadDark : ResourceDictionary
{
    public TokensHomesteadDark()
    {
        AvaloniaXamlLoader.Load(this);
    }
}
