<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <RootNamespace>AvaWpf.Gallery.Desktop</RootNamespace>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <IsAotCompatible>true</IsAotCompatible>
    <!-- IL2104/IL3053: summary warnings from the Avalonia.Controls.DataGrid package. -->
    <NoWarn>$(NoWarn);IL2104;IL3053</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Wayland" />
    <PackageReference Include="Avalonia.Headless" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Condition="'$(Configuration)' == 'Debug'" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AvaWpf.Gallery\AvaWpf.Gallery.csproj" />
  </ItemGroup>

</Project>
