#!/usr/bin/env python3
"""Generates the Fluent icon outputs of AvaWpf.

Outputs (checked in; never edited by hand):

  src/AvaWpf.Fonts/Assets/Fonts/AvaWpfFluentGlyphs.ttf
      A subset of FluentSystemIcons-Regular.ttf with only the glyphs named in
      segoe-to-fluentui.toml. It keeps the Fluent UI codepoints and is renamed
      to the family "AvaWpf Fluent Glyphs", so it never clashes with the full
      font from AvaWpf.Icons.
  src/AvaWpf.Theme/Glyphs/FluentGlyph.g.cs
      One constant per Segoe glyph name, holding the Fluent UI codepoint.
  src/AvaWpf.Icons/FluentIcon.g.cs
      One constant per icon name and size of the full fonts.

Inputs:

  segoe-to-fluentui.toml                    the hand-written glyph map
  upstream/FluentSystemIcons-{Regular,Filled}.json   name -> codepoint maps
  src/AvaWpf.Icons/Assets/FluentSystemIcons-Regular.ttf  (unmodified upstream font)

Usage:

  python3 tools/gen-icons/gen-icons.py [--root DIR] [--check]

--root (or AVAWPF_ROOT) is the repository root; the default is two levels
above this script. --check regenerates into a temporary directory and fails on
any difference. The subset font is compared by its codepoint -> glyph outline
map, not byte for byte, because fontTools versions write slightly different
tables.

Requires fontTools (pip install fonttools).
"""

import argparse
import hashlib
import json
import os
import re
import sys
import tempfile
import tomllib

from fontTools import subset
from fontTools.ttLib import TTFont

FAMILY = "AvaWpf Fluent Glyphs"


def pascal(name: str) -> str:
    parts = re.split(r"[_\s]+", name)
    return "".join(p[:1].upper() + p[1:] for p in parts if p)


def load_map(root: str):
    with open(os.path.join(root, "tools/gen-icons/segoe-to-fluentui.toml"), "rb") as f:
        data = tomllib.load(f)
    entries = []
    for section in ("wpf", "extra"):
        for cp, entry in data.get(section, {}).items():
            entries.append((section, cp.upper(), entry["name"], entry["icon"]))
    return entries


def load_upstream(root: str, style: str):
    with open(os.path.join(root, f"tools/gen-icons/upstream/FluentSystemIcons-{style}.json"), encoding="utf-8") as f:
        return json.load(f)


def write_glyph_class(root: str, out_dir: str, entries, regular):
    lines = [
        "// <auto-generated>",
        "// Generated by tools/gen-icons/gen-icons.py from segoe-to-fluentui.toml. Do not edit.",
        "// </auto-generated>",
        "namespace AvaWpf;",
        "",
        "/// <summary>",
        "/// The glyphs of the bundled Fluent icon subset (the <c>Fluent.SymbolThemeFontFamily</c> token). Each constant is",
        "/// named for the Segoe Fluent Icons glyph that WPF Fluent uses and holds the Fluent UI System Icons codepoint.",
        "/// </summary>",
        "public static class FluentGlyph",
        "{",
    ]
    seen = set()
    for section, cp, name, icon in entries:
        if name in seen:
            raise SystemExit(f"duplicate glyph name {name}")
        seen.add(name)
        key = f"ic_fluent_{icon}"
        if key not in regular:
            raise SystemExit(f"{cp}: {key} is not in FluentSystemIcons-Regular.json")
        code = regular[key]
        origin = "WPF Fluent" if section == "wpf" else "AvaWpf templates"
        lines.append(f"    /// <summary>Segoe <c>U+{cp}</c> ({origin}); Fluent UI <c>{icon}</c>.</summary>")
        lines.append(f"    public const string {name} = \"{chr_escape(code)}\";")
        lines.append("")
    if lines[-1] == "":
        lines.pop()
    lines.append("}")
    path = os.path.join(out_dir, "src/AvaWpf.Theme/Glyphs/FluentGlyph.g.cs")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")


def write_icon_class(out_dir: str, regular, filled):
    lines = [
        "// <auto-generated>",
        "// Generated by tools/gen-icons/gen-icons.py from the FluentSystemIcons-*.json maps. Do not edit.",
        "// </auto-generated>",
        "namespace AvaWpf.Icons;",
        "",
        "/// <summary>",
        "/// Every Fluent UI System Icons glyph by name and size. <c>*Regular</c> glyphs render with the",
        "/// <c>FluentIconsRegular</c> family and <c>*Filled</c> glyphs with <c>FluentIconsFilled</c>.",
        "/// </summary>",
        "public static class FluentIcon",
        "{",
    ]
    names = {}
    for style, table in (("Regular", regular), ("Filled", filled)):
        for key, code in table.items():
            if not key.startswith("ic_fluent_"):
                continue
            name = pascal(key[len("ic_fluent_"):])
            if name[:1].isdigit():
                name = "_" + name
            if name in names:
                continue
            names[name] = code
    for name in sorted(names):
        lines.append(f"    /// <summary>U+{names[name]:04X}.</summary>")
        lines.append(f"    public const string {name} = \"{chr_escape(names[name])}\";")
    lines.append("}")
    path = os.path.join(out_dir, "src/AvaWpf.Icons/FluentIcon.g.cs")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")


def chr_escape(code: int) -> str:
    if code > 0xFFFF:
        return f"\\U{code:08X}"
    return f"\\u{code:04X}"


def load_scales(root: str):
    """Icon name -> outline scale, for entries with a `scale` (a glyph drawn for a smaller em than its stand-in)."""
    with open(os.path.join(root, "tools/gen-icons/segoe-to-fluentui.toml"), "rb") as f:
        data = tomllib.load(f)
    return {e["icon"]: float(e["scale"]) for section in ("wpf", "extra") for e in data.get(section, {}).values() if "scale" in e}


def load_filled(root: str):
    """Icon names of entries with `style = "filled"`: their outline comes from the Filled font (a solid Segoe glyph)."""
    with open(os.path.join(root, "tools/gen-icons/segoe-to-fluentui.toml"), "rb") as f:
        data = tomllib.load(f)
    return [e["icon"] for section in ("wpf", "extra") for e in data.get(section, {}).values() if e.get("style") == "filled"]


def fill_glyphs(root: str, font, regular, icons):
    """Replaces the outlines of the given (regular) icons with their filled counterparts, keeping codepoint and name."""
    if not icons:
        return
    import copy
    filled_font = TTFont(os.path.join(root, "src/AvaWpf.Icons/Assets/FluentSystemIcons-Filled.ttf"))
    filled = load_upstream(root, "Filled")
    assert filled_font["head"].unitsPerEm == font["head"].unitsPerEm
    cmap, filled_cmap = font.getBestCmap(), filled_font.getBestCmap()
    for icon in icons:
        name = cmap[regular[f"ic_fluent_{icon}"]]
        source = filled_cmap[filled[f"ic_fluent_{icon.removesuffix('_regular')}_filled"]]
        glyph = copy.deepcopy(filled_font["glyf"][source])
        glyph.expand(filled_font["glyf"])
        font["glyf"][name] = glyph
        font["glyf"][name].recalcBounds(font["glyf"])
        font["hmtx"][name] = filled_font["hmtx"][source]


def scale_glyphs(font, regular, scales):
    """Scales the outlines of the given icons about the centre of their bounds, keeping the advance width."""
    glyf = font["glyf"]
    cmap = font.getBestCmap()
    for icon, factor in scales.items():
        name = cmap[regular[f"ic_fluent_{icon}"]]
        glyph = glyf[name]
        coords = glyph.coordinates
        xs = [x for x, _ in coords]
        ys = [y for _, y in coords]
        cx, cy = (min(xs) + max(xs)) / 2, (min(ys) + max(ys)) / 2
        for i, (x, y) in enumerate(coords):
            coords[i] = (round(cx + (x - cx) * factor), round(cy + (y - cy) * factor))
        glyph.recalcBounds(glyf)


def write_subset(root: str, out_dir: str, entries, regular):
    src = os.path.join(root, "src/AvaWpf.Icons/Assets/FluentSystemIcons-Regular.ttf")
    codes = sorted({regular[f"ic_fluent_{icon}"] for _, _, _, icon in entries})
    options = subset.Options()
    options.layout_features = []
    options.name_IDs = ["*"]
    options.notdef_outline = True
    options.recalc_timestamp = False
    font = subset.load_font(src, options)
    subsetter = subset.Subsetter(options)
    subsetter.populate(unicodes=codes)
    subsetter.subset(font)
    fill_glyphs(root, font, regular, load_filled(root))
    scale_glyphs(font, regular, load_scales(root))
    name = font["name"]
    for record in list(name.names):
        if record.nameID in (1, 4, 16):
            record.string = FAMILY
        elif record.nameID == 6:
            record.string = FAMILY.replace(" ", "")
        elif record.nameID in (2, 17):
            record.string = "Regular"
    # A fixed timestamp keeps the output stable between runs.
    font["head"].created = font["head"].modified = 3_800_000_000
    path = os.path.join(out_dir, "src/AvaWpf.Fonts/Assets/Fonts/AvaWpfFluentGlyphs.ttf")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    subset.save_font(font, path, options)


def subset_signature(path: str) -> str:
    font = TTFont(path)
    cmap = font.getBestCmap()
    glyf = font["glyf"] if "glyf" in font else None
    h = hashlib.sha256()
    h.update(font["name"].getDebugName(1).encode())
    for code in sorted(cmap):
        h.update(f"{code:X}:".encode())
        if glyf is not None:
            g = glyf[cmap[code]]
            coords, ends, _ = g.getCoordinates(glyf)
            h.update(repr((list(coords), ends)).encode())
    return h.hexdigest()


def generate(root: str, out_dir: str):
    entries = load_map(root)
    regular = load_upstream(root, "Regular")
    filled = load_upstream(root, "Filled")
    write_glyph_class(root, out_dir, entries, regular)
    write_icon_class(out_dir, regular, filled)
    write_subset(root, out_dir, entries, regular)


OUTPUTS = [
    "src/AvaWpf.Theme/Glyphs/FluentGlyph.g.cs",
    "src/AvaWpf.Icons/FluentIcon.g.cs",
]
SUBSET = "src/AvaWpf.Fonts/Assets/Fonts/AvaWpfFluentGlyphs.ttf"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    default_root = os.environ.get("AVAWPF_ROOT") or os.path.normpath(os.path.join(os.path.dirname(__file__), "..", ".."))
    parser.add_argument("--root", default=default_root)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = os.path.abspath(args.root)

    if not args.check:
        generate(root, root)
        print("gen-icons: wrote", ", ".join(OUTPUTS + [SUBSET]))
        return 0

    with tempfile.TemporaryDirectory() as tmp:
        generate(root, tmp)
        failed = False
        for rel in OUTPUTS:
            with open(os.path.join(root, rel), encoding="utf-8") as a, open(os.path.join(tmp, rel), encoding="utf-8") as b:
                if a.read() != b.read():
                    print(f"gen-icons --check: {rel} is out of date", file=sys.stderr)
                    failed = True
        if subset_signature(os.path.join(root, SUBSET)) != subset_signature(os.path.join(tmp, SUBSET)):
            print(f"gen-icons --check: {SUBSET} is out of date", file=sys.stderr)
            failed = True
        if failed:
            print("Run python3 tools/gen-icons/gen-icons.py and commit the result.", file=sys.stderr)
            return 1
    print("gen-icons --check: up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
