// <auto-generated>
// Generated by tools/wpf-tokens/wpf-tokens.cs. Do not edit.
// </auto-generated>
using Avalonia.Controls;
using Avalonia.Markup.Xaml;

namespace AvaWpf.Themes.Royale;

/// <summary>The Royale NormalColor, Light tokens.</summary>
internal partial class TokensLight : ResourceDictionary
{
    public TokensLight()
    {
        AvaloniaXamlLoader.Load(this);
    }
}
