// <auto-generated>
// Generated by tools/wpf-tokens/wpf-tokens.cs. Do not edit.
// </auto-generated>
using Avalonia.Controls;
using Avalonia.Markup.Xaml;

namespace AvaWpf.Themes.AeroLite;

/// <summary>The AeroLite Default, Dark (derived; see tools/wpf-tokens/dark/aerolite.toml) tokens.</summary>
internal partial class TokensDark : ResourceDictionary
{
    public TokensDark()
    {
        AvaloniaXamlLoader.Load(this);
    }
}
