<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Avalonia.Headless.XUnit" />
    <PackageReference Include="Avalonia.Skia" />
    <PackageReference Include="Avalonia.HarfBuzz" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\AvaWpf.Animations\AvaWpf.Animations.csproj" />
  </ItemGroup>
</Project>
