// <auto-generated>
// Generated by tools/gen-icons/gen-icons.py from segoe-to-fluentui.toml. Do not edit.
// </auto-generated>
namespace AvaWpf;

/// <summary>
/// The glyphs of the bundled Fluent icon subset (the <c>Fluent.SymbolThemeFontFamily</c> token). Each constant is
/// named for the Segoe Fluent Icons glyph that WPF Fluent uses and holds the Fluent UI System Icons codepoint.
/// </summary>
public static class FluentGlyph
{
    /// <summary>Segoe <c>U+E70D</c> (WPF Fluent); Fluent UI <c>chevron_down_16_regular</c>.</summary>
    public const string ChevronDown = "\uF2A2";

    /// <summary>Segoe <c>U+E70E</c> (WPF Fluent); Fluent UI <c>chevron_up_16_regular</c>.</summary>
    public const string ChevronUp = "\uF2B5";

    /// <summary>Segoe <c>U+E73E</c> (WPF Fluent); Fluent UI <c>checkmark_16_regular</c>.</summary>
    public const string CheckMark = "\uE305";

    /// <summary>Segoe <c>U+E76B</c> (WPF Fluent); Fluent UI <c>chevron_left_16_regular</c>.</summary>
    public const string ChevronLeft = "\uF2A9";

    /// <summary>Segoe <c>U+E76C</c> (WPF Fluent); Fluent UI <c>chevron_right_16_regular</c>.</summary>
    public const string ChevronRight = "\uF2AF";

    /// <summary>Segoe <c>U+E787</c> (WPF Fluent); Fluent UI <c>calendar_ltr_16_regular</c>.</summary>
    public const string Calendar = "\uE24D";

    /// <summary>Segoe <c>U+E894</c> (WPF Fluent); Fluent UI <c>dismiss_16_regular</c>.</summary>
    public const string Clear = "\uF368";

    /// <summary>Segoe <c>U+E9AE</c> (WPF Fluent); Fluent UI <c>subtract_16_regular</c>.</summary>
    public const string CheckboxIndeterminate = "\uEBCF";

    /// <summary>Segoe <c>U+EDD9</c> (WPF Fluent); Fluent UI <c>caret_left_12_regular</c>.</summary>
    public const string CaretLeftSolid8 = "\uF263";

    /// <summary>Segoe <c>U+EDDA</c> (WPF Fluent); Fluent UI <c>caret_right_12_regular</c>.</summary>
    public const string CaretRightSolid8 = "\uF267";

    /// <summary>Segoe <c>U+EDDB</c> (WPF Fluent); Fluent UI <c>caret_up_12_regular</c>.</summary>
    public const string CaretUpSolid8 = "\uE2A7";

    /// <summary>Segoe <c>U+EDDC</c> (WPF Fluent); Fluent UI <c>caret_down_12_regular</c>.</summary>
    public const string CaretDownSolid8 = "\uF25F";

    /// <summary>Segoe <c>U+F08E</c> (WPF Fluent); Fluent UI <c>arrow_sort_up_16_regular</c>.</summary>
    public const string SortUp = "\uF1B3";

    /// <summary>Segoe <c>U+F090</c> (WPF Fluent); Fluent UI <c>arrow_sort_down_16_regular</c>.</summary>
    public const string SortDown = "\uF1AC";

    /// <summary>Segoe <c>U+F169</c> (WPF Fluent); Fluent UI <c>resize_small_16_regular</c>.</summary>
    public const string ResizeGrip = "\uEA18";

    /// <summary>Segoe <c>U+E921</c> (AvaWpf templates); Fluent UI <c>line_horizontal_1_16_regular</c>.</summary>
    public const string ChromeMinimize = "\U000F02B7";

    /// <summary>Segoe <c>U+E922</c> (AvaWpf templates); Fluent UI <c>square_16_regular</c>.</summary>
    public const string ChromeMaximize = "\uEB74";

    /// <summary>Segoe <c>U+E923</c> (AvaWpf templates); Fluent UI <c>square_multiple_16_regular</c>.</summary>
    public const string ChromeRestore = "\uEB95";

    /// <summary>Segoe <c>U+E8BB</c> (AvaWpf templates); Fluent UI <c>dismiss_16_regular</c>.</summary>
    public const string ChromeClose = "\uF368";

    /// <summary>Segoe <c>U+E710</c> (AvaWpf templates); Fluent UI <c>add_16_regular</c>.</summary>
    public const string Add = "\uF108";

    /// <summary>Segoe <c>U+E738</c> (AvaWpf templates); Fluent UI <c>subtract_16_regular</c>.</summary>
    public const string Remove = "\uEBCF";

    /// <summary>Segoe <c>U+E712</c> (AvaWpf templates); Fluent UI <c>more_horizontal_16_regular</c>.</summary>
    public const string More = "\uE823";

    /// <summary>Segoe <c>U+E7B3</c> (AvaWpf templates); Fluent UI <c>eye_16_regular</c>.</summary>
    public const string RevealPassword = "\uE5F1";

    /// <summary>Segoe <c>U+E823</c> (AvaWpf templates); Fluent UI <c>clock_16_regular</c>.</summary>
    public const string Clock = "\uF2DC";

    /// <summary>Segoe <c>U+E946</c> (AvaWpf templates); Fluent UI <c>info_16_regular</c>.</summary>
    public const string Info = "\uF4A2";

    /// <summary>Segoe <c>U+E7BA</c> (AvaWpf templates); Fluent UI <c>warning_16_regular</c>.</summary>
    public const string Warning = "\uF868";

    /// <summary>Segoe <c>U+EA39</c> (AvaWpf templates); Fluent UI <c>error_circle_16_regular</c>.</summary>
    public const string ErrorBadge = "\uF3F0";

    /// <summary>Segoe <c>U+E72C</c> (AvaWpf templates); Fluent UI <c>arrow_clockwise_16_regular</c>.</summary>
    public const string Refresh = "\uE0AA";

    /// <summary>Segoe <c>U+E700</c> (AvaWpf templates); Fluent UI <c>navigation_16_regular</c>.</summary>
    public const string GlobalNavigationButton = "\uE85F";

    /// <summary>Segoe <c>U+E72B</c> (AvaWpf templates); Fluent UI <c>arrow_left_16_regular</c>.</summary>
    public const string Back = "\uF184";
}
