<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>AvaWpf.Icons</RootNamespace>
    <PackageId>AvaWpf.Icons</PackageId>
    <Description>The full Fluent UI System Icons fonts (Regular and Filled) with a name to codepoint class.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />

  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets/**/*.ttf" />
    <None Include="Assets/**/*.txt" Pack="true" PackagePath="licenses\" />
  </ItemGroup>

</Project>
